nome = str(input('Digite seu nome: ')).strip()
print('Olá {} vou te mostrar algumas informações sobre seu nome'.format(nome))
print('Tudo maiuscula:', nome.upper())
print('Tudo minuscula:', nome.lower())
print('Quantidade de letras:', len(nome) -nome.count(' '))
#print('Seu primeiro nome tem {} letras:'.format(nome.find(' ')))
separa = nome.split()
print('Seu primeiro nome é {} e ele tem {} letras'.format(separa[0], len(separa[0])))
